export const Product = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SET_CARTS: "SET_CARTS",
  SET_PAGINATION: "SET_PAGINATION",
  SET_VALUE: "SET_VALUE",
  SET_SEARCH_VALUE: "SET_SEARCH_VALUE",
  UPDATE_PRODUCT: " UPDATE_PRODUCT",
  LOADING: "LOADING",
 
};
